/**
 * Post-build: clean up unwanted files and update manifest.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.resolve(__dirname, "../dist");

// Remove HTML files generated by Rsbuild (not needed for content scripts)
for (const file of fs.readdirSync(DIST)) {
  if (file.endsWith(".html")) {
    fs.unlinkSync(path.join(DIST, file));
    console.log(`Removed ${file}`);
  }
}

// Update manifest with actual chunk filenames
execSync("node scripts/generate-manifest.mjs", {
  cwd: path.resolve(__dirname, ".."),
  stdio: "inherit",
});
